### ISSUE TITLE
Deleting user doesn't delete rows in sitePermissions table.

### ISSUE THREAD

**Issue by ileana-heaton** [BYU-ODH/yvideo#106]
Deleting a user should delete all traces of the user from the DB, but it's at least leaving behind rows in the sitePermissions table with their userId. Then, if the same person logs back in, it creates a new userId for them and their old sitePermissions remain in the DB with their previous userId. (may do the same for other tables if they had information in them, not sure though.)

**Comment by bradenhutch** [comment]
The batchsql function in the user model was malformed or something so I replaced it with individual queries.
