### ISSUE TITLE
Get rid of annoying SSL messages

### ISSUE THREAD

**Issue by bradenhutch** [BYU-ODH/yvideo#113]
Messages like the one below clutter our console when running basically anything, especially tests.

```WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.```

They are also showing in our Travis builds.

**Comment by bradenhutch** [comment]
adding &useSSL=false to the end of our db.default.url in the conf file fixes this, but is this what we want to do? @verdude

**Comment by verdude** [comment]
That's fine for development and testing but we'll have to set up keys for mysql once we get the production server running.
Closing this here but moving it over to the [https://github.com/byu-odh/yvideo-deploy](yvideo-deploy) for reference.
