### ISSUE TITLE
Add metadata to feedback emails

### ISSUE THREAD

**Issue by verdude** [BYU-ODH/yvideo#119]
current page 
netid
stack trace

**Comment by bradenhutch** [comment]
Collecting information about someone who is giving feedback could be interpreted as an invasion of privacy. When we do #122 we can maybe give users the option to share this information, but we probably shouldn't collect it without their knowledge. Also exposing stack traces in any way on a production site could be a security risk.
For 500 errors we already collect the user ID along with any feedback they give which should be sufficient.
