### ISSUE TITLE
Endpoint for recently viewed content and previews

### ISSUE THREAD

**Issue by bradenhutch** [BYU-ODH/yvideo#124]
```
/user/recent
[{
  video_id
  contentname
  thumb_url
  collection_name
 },
 {
  ...
 }]

/user/previews
[{
  collection_id
  collection_name
  thumb-url
  count
 },
 {
  ...
 }]
```
Grant mentioned that he would need these endpoints for serving the users homepage according to @siratus 's designs. 

We might need to add an entry to the users table/new table to keep track of a user's recently viewed content. We would also need to add an endpoint to update the recents when a user views a new content.

I think we already have what we need for the previews endpoint, but could streamline it by making one specifically for it.

**Comment by verdude** [comment]
```sql
userViews {
  id BIGINT
  userId BIGINT
  contentId BIGINT
}
```

Add a user views table to keep track of recently viewed content.

**Comment by verdude** [comment]
Also add an increment viewcount endpoint for content

**Comment by verdude** [comment]
8d260920a8310c2e9947970a0bb59c814d0fea16
