### ISSUE TITLE
Integrate h2 in memory database for testing

### ISSUE THREAD

**Issue by bradenhutch** [BYU-ODH/yvideo#125]
https://www.playframework.com/documentation/2.6.x/ScalaTestingWithDatabases

**Comment by verdude** [comment]
a97deab236195c477b28eb39589d537649e4f6f3

**Comment by verdude** [comment]
Still need to implement db setup and teardown.

**Comment by verdude** [comment]
e80a4241580df5b43da89b77cfb07a38708adcca
