### ISSUE TITLE
Collaborative Subtitle/Annotations Sharing

### ISSUE THREAD

**Issue by JKJensen** [BYU-ODH/yvideo#24]
**Problem:** 
Right now when a user creates subtitles, other users can't edit those subtitles. This is an issue when Professors and TA's can't edit subtitles together. (But good because normal users can't effect others content). This is an okay system for Ayamel world, but not Y-Videos.

**Proposed solution**:
Those with the Admin, Professor, and TA permissions can freely edit each others subtitles/annotations.

**Admin:**
Can freely edit subtitles/annotations across the site

**Professor and TA:**
Can edit subtitles/annotations on content that is inside courses that they own.

For content not inside courses, only the content owner (whoever uploaded it) can edit subtitles for it.

Professor and TA permissions contain a list of courses that they share, and they can edit content in those courses.

Note that TAs can be a regular student in some courses, and a TA in others. They should only have permission to edit the courses that they are the TA of.

**Comment by bradenhutch** [comment]
This will no longer be an issue since content will be owned by collection and can be fully edited by a collection owner or TA
