### ISSUE TITLE
Remove My Content

### ISSUE THREAD

**Issue by trevren11** [BYU-ODH/yvideo#33]
Students will no longer have the option to upload content. Remove feature

**Comment by bradenhutch** [comment]
Please double check to make sure that teachers and admins can still keep this feature. 

Also, there are some students that I have helped (graduate students that are using ayamel to do research by making content with different annotations/subtitles) so that might be a reason to keep this feature. However it might be easier just to make exceptions for them (i.e. make a separate password based account for them with teacher privileges).

**Comment by gliese1337** [comment]
It may be simpler (and would certainly reduce code complexity by getting rid of a bunch of special cases) to simply require admins, teachers, grad students, etc. to put "My Content" into a course. One could even keep the "My Content" link in the menu for those people, but just have it go to a particular, user-configurable, course page.

Then every piece of content always belongs to a course (which eliminates a lot of conditional checks), all of the code relating to the special "My Content" page goes away, and you just need to add a single new permission that can be turned on on a case-by-case basis to give the user the ability to select a particular course to use as "My Content".

**Comment by bradenhutch** [comment]
Sounds like a great idea to me. Just make sure that the ability to add video to a course from "my content" is replaced with the ability to add content that is already present in another course. Some people might want to upload content and edit it (subtitles etc.) in an environment that is not visible to students.

**Comment by gliese1337** [comment]
All of the plumbing for that should already be in place, via the "clone content" mechanism. Just need to make sure that the right buttons are in the right places to access that API.

It might be a good idea to supplement with "move content", however.

**Comment by bradenhutch** [comment]
This will also fix a lot of issues that TAs and research assistants etc. are having. Currently, only the creator of the content (or an admin) has full edit/configuration privileges. This is difficult for cases where teachers want to leave content creation and editing up to TAs. Maybe the easiest way to approach this would be to give content ownership to a course, thus making anyone with "course admin" privileges for a course equivalent to the content owner for said content.

**Comment by verdude** [comment]
d2d197971a9fbc0ebd5031ff5494c070b56787de
